-- LSP configuration for C / C++ / Objective-C
-- Uses clangd as the language server, cpplint via EFM for linting, and
-- the cpptools DAP adapter (OpenDebugAD7) for debugging.
---@module "modules.base.configs.languages.lsp.servers.cpp"
local ft = require("modules.base.configs.languages.lsp.file_types")

local dap_utils = require("modules.base.configs.languages.lsp.dap_utils")

---@type string[]  Root-directory markers for C/C++ projects
local root_markers = {
    ".clangd",
    ".clang-tidy",
    ".clang-format",
    "compile_commands.json", -- generated by CMake / Bear; required for accurate includes
    "compile_flags.txt", -- simpler alternative to compile_commands.json
    "configure.ac", -- autoconf-based projects
    ".git",
}

---Sends the clangd-specific textDocument/switchSourceHeader request to toggle
---between a .h/.hpp header and its corresponding .c/.cpp source file.
---@param bufnr integer  Buffer whose source/header should be toggled
local function switch_source_header(bufnr)
    local method_name = "textDocument/switchSourceHeader"
    local client = vim.lsp.get_clients({ bufnr = bufnr, name = "clangd" })[1]
    if not client then
        return vim.notify(
            ("method %s is not supported by any servers active on the current buffer"):format(method_name)
        )
    end
    local params = vim.lsp.util.make_text_document_params(bufnr)
    client.request(method_name, params, function(err, result)
        if err then
            error(tostring(err))
        end
        if not result then
            vim.notify("corresponding file cannot be determined")
            return
        end
        vim.cmd.edit(vim.uri_to_fname(result))
    end, bufnr)
end

---Queries clangd for symbol metadata at the cursor position and displays it
---in a small floating window (container name + symbol name).
local function symbol_info()
    local bufnr = vim.api.nvim_get_current_buf()
    local clangd_client = vim.lsp.get_clients({ bufnr = bufnr, name = "clangd" })[1]
    ---@diagnostic disable-next-line: missing-parameter
    if not clangd_client or not clangd_client.supports_method("textDocument/symbolInfo") then
        return vim.notify("Clangd client not found", vim.log.levels.ERROR)
    end
    local win = vim.api.nvim_get_current_win()
    local params = vim.lsp.util.make_position_params(win, clangd_client.offset_encoding)
    clangd_client.request("textDocument/symbolInfo", params, function(err, res)
        if err or #res == 0 then
            -- Clangd always returns an error, there is not reason to parse it
            return
        end
        local container = string.format("container: %s", res[1].containerName) ---@type string
        local name = string.format("name: %s", res[1].name) ---@type string
        vim.lsp.util.open_floating_preview({ name, container }, "", {
            height = 2,
            width = math.max(string.len(name), string.len(container)),
            focusable = false,
            focus = false,
            border = "single",
            title = "Symbol Info",
        })
    end, bufnr)
end

-- Register cpplint as a linter through EFM so clangd handles completions
-- while a separate process handles Google-style lint rules.
local efm_config = {
    {
        server_name = "cpplint",
        lintCommand = "cpplint ${INPUT}",
        lintStdin = true,
        rootMarkers = { "cpplint.cfg" },
    },
}

return {
    lsp = {
        root_patterns = root_markers,
        config = {
            name = "cpp",
            cmd = {
                "clangd",
                "--clang-tidy", -- enable clang-tidy diagnostics in-editor
                "--header-insertion=iwyu", -- use Include What You Use for auto-insertions
                "--background-index", -- build the global symbol index asynchronously
                "--suggest-missing-includes",
            },
            ---Called by nvim-lspconfig after the client attaches to a buffer.
            ---@param client any
            ---@param bufnr  integer
            on_attach = function(client, bufnr)
                if client.server_capabilities.documentSymbolProvider then
                    require("nvim-navic").attach(client, bufnr)
                end
                -- Register buffer-local commands for clangd-specific features
                vim.api.nvim_buf_create_user_command(0, "LspClangdSwitchSourceHeader", function()
                    switch_source_header(0)
                end, { desc = "Switch between source/header" })
                vim.api.nvim_buf_create_user_command(0, "LspClangdShowSymbolInfo", function()
                    symbol_info()
                end, { desc = "Show symbol info" })
            end,
            settings = {
                clangd = {
                    callHierarchy = true,
                    semanticHighlighting = true,
                    checkUpdates = true,
                    fallbackFlags = { "-std=c++17" }, -- default standard when no compile_commands.json
                },
            },
        },
    },
    efm = {
        filetypes = ft.cpp.filetypes,
        tools = efm_config,
    },
    dap = {
        -- DAP: use the cpptools (Microsoft C++ Extension) OpenDebugAD7 binary.
        adapters = {
            cppdbg = {
                id = "cppdbg",
                type = "executable",
                command = vim.fn.stdpath("data")
                    .. "/mason"
                    .. "/packages/cpptools/extension/debugAdapters/bin/OpenDebugAD7",
            },
        },
        configurations = {
            cpp = {
                {
                    name = "Launch file",
                    type = "cppdbg",
                    request = "launch",
                    program = function()
                        return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
                    end,
                    cwd = "${workspaceFolder}",
                    stopOnEntry = true, -- pause at entry point so the user can inspect state early
                    setupCommands = {
                        {
                            text = "-enable-pretty-printing",
                            description = "enable pretty printing",
                            ignoreFailures = false,
                        },
                    },
                },
                {
                    name = "Attach to gdbserver :1234",
                    type = "cppdbg",
                    request = "attach",
                    processId = dap_utils.fzf_process_picker, -- interactive process picker via fzf
                    MIMode = "gdb",
                    miDebuggerServerAddress = "localhost:1234",
                    miDebuggerPath = "/usr/bin/gdb",
                    cwd = "${workspaceFolder}",
                    program = function()
                        return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
                    end,
                    useExtendedRemote = true, -- allows re-attach after process restart
                    setupCommands = {
                        {
                            text = "-enable-pretty-printing",
                            description = "enable pretty printing",
                            ignoreFailures = false,
                        },
                    },
                },
            },
        },
    },
}

-- vim: foldmethod=indent foldlevel=1
