return {
    cmp = {
        Folder = "  (Folder)",
        File = "  (File)",
        Package = "  (Package)",
        Module = "  (Module)",
        Namespace = "  (Namespace)",
        Interface = " 練 (Interface)",
        Constructor = "   (Constructor)",
        Enum = " 練 (Enum)",
        EnumMember = "  (EnumMember)",
        Class = "  (Class)",
        Method = "  (Method)",
        Function = "  (Function)",
        Property = " 襁 (Property)",
        Field = " 濾 (Field)",
        Constant = "  (Constant)",
        Variable = " 咽 (Variable)",
        String = "  (String)",
        Number = "  (Number)",
        Boolean = " ◩ (Boolean)",
        Array = "  (Array)",
        Object = "  (Object)",
        Key = "  (Key)",
        Null = " ﳠ (Null)",
        Struct = "  (Struct)",
        Event = "  (Event)",
        Operator = "  (Operator)",
        TypeParameter = "  (TypeParameter)",
        Text = "  (Text) ",
        Unit = "  (Unit)",
        Value = "  (Value)",
        Keyword = "  (Keyword)",
        Snippet = "  (Snippet)",
        Color = "  (Color)",
        Reference = "  (Reference)",
    },
    lsp = {
        File = " ",
        Module = " ",
        Namespace = " ",
        Package = " ",
        Class = " ",
        Method = " ",
        Property = "襁 ",
        Field = "濾 ",
        Constructor = "  ",
        Enum = "練 ",
        Interface = "練 ",
        Function = " ",
        Variable = "咽 ",
        Constant = " ",
        String = " ",
        Number = " ",
        Boolean = "◩ ",
        Array = " ",
        Object = " ",
        Key = " ",
        Null = "ﳠ",
        EnumMember = " ",
        Struct = " ",
        Event = " ",
        Operator = " ",
        TypeParameter = " ",
    },
    outline = {
        File = { icon = "", hl = "TSFile" },
        Module = { icon = "", hl = "TSNamespace" },
        Namespace = { icon = "", hl = "TSNamespace" },
        Package = { icon = "", hl = "TSNamespace" },
        Class = { icon = "", hl = "TSType" },
        Method = { icon = "", hl = "TSMethod" },
        Property = { icon = "襁", hl = "TSMethod" },
        Field = { icon = "濾", hl = "TSField" },
        Constructor = { icon = "", hl = "TSConstructor" },
        Enum = { icon = "練", hl = "TSType" },
        Interface = { icon = "練", hl = "TSType" },
        Function = { icon = "", hl = "TSFunction" },
        Variable = { icon = "咽", hl = "TSConstant" },
        Constant = { icon = "", hl = "TSConstant" },
        String = { icon = "", hl = "TSString" },
        Number = { icon = "", hl = "TSNumber" },
        Boolean = { icon = "◩", hl = "TSBoolean" },
        Array = { icon = "", hl = "TSConstant" },
        Object = { icon = "", hl = "TSType" },
        Key = { icon = "", hl = "TSType" },
        Null = { icon = "ﳠ", hl = "TSType" },
        EnumMember = { icon = "", hl = "TSField" },
        Struct = { icon = "", hl = "TSType" },
        Event = { icon = "", hl = "TSType" },
        Operator = { icon = "", hl = "TSOperator" },
        TypeParameter = { icon = "", hl = "TSParameter" },
    },
    hl = {
        File = "TSFile",
        Module = "TSNamespace",
        Namespace = "TSNamespace",
        Package = "TSNamespace",
        Class = "TSType",
        Method = "TSMethod",
        Property = "TSMethod",
        Field = "TSField",
        Constructor = "TSConstructor",
        Enum = "TSType",
        Interface = "TSType",
        Function = "TSFunction",
        Variable = "TSConstant",
        Constant = "TSConstant",
        String = "TSString",
        Number = "TSNumber",
        Boolean = "TSBoolean",
        Array = "TSConstant",
        Object = "TSType",
        Key = "TSType",
        Null = "TSType",
        EnumMember = "TSField",
        Struct = "TSType",
        Event = "TSType",
        Operator = "TSOperator",
        TypeParameter = "TSParameter",
    },
}
